name: Angular CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install Dependencies
      run: npm i -g @angular/cli
    - name: Clean Node Modules
      run: rm -rf node_modules package-lock.json
    - name: Install Node Modules
      run: npm install
    - name: Build
      run: ng build --prod
    # - name: Test
    #   run: ng test --browsers=ChromeHeadless --no-watch --code-coverage --source-map=false
