name: Angular CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install Dependencies
      run: npm ci
      run: npm install
    - name: Build
      run: ng test --browsers=ChromeHeadless --no-watch --code-coverage --source-map=false
      run: ng run build --configuration=production
    - name: Test